name: Github Pages Deploy

on:
  push:
    branches:
      - "urlgen"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        
      - name: List project folders
        run: ls

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
            fqdn: ujian.smadewisartika.sch.id.belajar.bio
            target_branch: gh-pages-urlgen
            build_dir: public
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
